# Generated by Django 3.2.4 on 2024-10-17 22:12

import django.core.validators
from django.db import migrations, models

def set_default_email(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    for profile in Profile.objects.filter(email__isnull=True):
        profile.email = f"user_{profile.owner_id}@example.com"
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[
                django.core.validators.MinValueValidator(0),
                django.core.validators.MaxValueValidator(120)
            ]),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, null=True),
        ),
        migrations.RunPython(set_default_email),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, null=False),
        ),
    ]

