# Generated by Django 3.2.4 on 2024-11-29 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241005_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(default=30, help_text='Cook time in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
